# commit to be tagged for new release
commit = "HEAD"

project_name = "Talos System Extensions"
github_repo = "siderolabs/extensions"
match_deps = "^github.com/((talos-systems|siderolabs)/[a-zA-Z0-9-]+)$"

# previous release
previous = "v1.6.4"

pre_release = false

preface = """\
See [Talos Linux documentation](https://www.talos.dev/v1.6/talos-guides/configuration/system-extensions/) for information on using system extensions.
"""

[notes]

    [notes.firmware]
        title = "New Firmware Extensions"
        description = """\
Two extensions: `qlogic-firmware` and `realtek-firmware` were backported from Talos 1.7 release.
"""


[make_deps]
